"""remove event description

Revision ID: 8f9df9b1af06
Revises: 3ceea68410bb
Create Date: 2026-09-20 16:16:53.003304

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f9df9b1af06"
down_revision: str | Sequence[str] | None = "3ceea68410bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
